### PR TITLE
Fix macOS bundle config

### LINKED ISSUE #404: MacOS Bundle issues
After installing F3D 1.3.0 bundle on MacOS,there are the following issues:

- config file is not found
- open with / double click opens F3D but without the file

### PR DESCRIPTION
**Pull request by Meakk**
Fix #404 and #403

### CODE REVIEW

**Comment by Meakk** [comment]
@mwestphal should be fine now, I'll test the package tomorrow morning again with a fresh brain

File: application/F3DConfigFileTools.cxx [hunk 1]
```diff
@@ -1,5 +1,7 @@
 #include "F3DConfigFileTools.h"
 
+#include "F3DConfig.h"
```
Comment (mwestphal) [inline application/F3DConfigFileTools.cxx:3]: While we cant fail to build, I think we can improve our CI to actually test the binary config flag.

it would be as simple as adding a reference file to the "Check Install" step of our CI. This image should be using the installed config file.

Ok to do in another PT though.

**Review by mwestphal — APPROVED** [review]

File: application/F3DConfigFileTools.cxx (hunk 1 above)
Comment (Meakk) [reply application/F3DConfigFileTools.cxx:3]: I have a better idea :)
