### PR TITLE
Fix Assimp lights

### LINKED ISSUE #445: Lighting issue with FBX format
**Describe the bug**
A .fbx with a light is not rendered correctly in F3D

**To Reproduce**
 0. Export a fbx with a point or spot light in blender, the default scene in blender is like that
 1. Open the file using `f3d --dry-run file.fbx`
 2. Cube is black

**Expected behavior**
Cube is visible

### PR DESCRIPTION
**Pull request by mwestphal**
- Fix lights transformation
- Workaround light attenuation issue
- Fix light angle
- Workareround light angle issue in collada
- Add Assimp Lights tests
- Fix #445 

This PR is impacted by assimp issues:

- https://github.com/assimp/assimp/issues/4949
- https://github.com/assimp/assimp/issues/4948

### CODE REVIEW

File: plugins/assimp/module/vtkF3DAssimpImporter.cxx [hunk 1]
```diff
@@ -713,19 +727,8 @@ class vtkF3DAssimpImporter::vtkInternals
...
-
-      mat->MultiplyPoint(position, position);
-      mat->MultiplyPoint(up, up);
-      mat->MultiplyPoint(focal, focal);
-
-      cam.second->SetPosition(position);
-      cam.second->SetViewUp(up);
-      cam.second->SetFocalPoint(focal);
+      // TODO Test this with/out animation
+      cam.second->SetModelTransformMatrix(this->NodeGlobalMatrix[cam.first]);
```
Comment (mwestphal) [inline plugins/assimp/module/vtkF3DAssimpImporter.cxx:731]: FYI will be removed from thisn PR

File: plugins/assimp/module/vtkF3DAssimpImporter.cxx [hunk 2]
```diff
@@ -109,31 +110,46 @@ class vtkF3DAssimpImporter::vtkInternals
...
+                light->SetConeAngle(vtkMath::DegreesFromRadians(aLight->mAngleOuterCone)/2);
+              }
               light->PositionalOn();
+              // Needed because of https://github.com/assimp/assimp/issues/4948
+              light->SetAttenuationValues(/*aLight->mAttenuationConstant*/ 1.0, aLight->mAttenuationLinear, aLight->mAttenuationQuadratic);
               break;
             case aiLightSourceType::aiLightSource_AREA:
+            case aiLightSourceType::aiLightSource_AMBIENT:
             default:
+              add = false;
```
Comment (Meakk) [inline plugins/assimp/module/vtkF3DAssimpImporter.cxx:142]: Can you just call `continue` to jump directly to the next loop iteration and drop the `add` variable?

Comment (mwestphal) [reply plugins/assimp/module/vtkF3DAssimpImporter.cxx:142]: yup

**Review by Meakk — APPROVED** [review]
