### PR TITLE
App: Rework handling of invalid file for better watch support

### LINKED ISSUE #2246: supported files stopped being `--watch`ed if they fail to load
**Describe the bug**
When a file of a supported type opened with the `--watch` option is overridden with erroneous data, overriding it again with a correct model does not trigger a reload automatically (but pressing the `up` key does).

**To Reproduce**

1.  run following python script to create and periodically override `watched.off` in your temp directory
```py
from time import sleep
from pathlib import Path
from tempfile import gettempdir

fn = Path(gettempdir()) / "watched.off"
delay = 3

while True:
    for name, off in {
        "a tetrahedron": "OFF\n4 4 0\n1 1 1\n1 -1 -1\n-1 1 -1\n-1 -1 1\n3 1 2 0\n3 0 2 3\n3 3 2 1\n3 1 0 3",
        "a cube": "OFF\n8 6 0\n-1 -1 -1\n-1 -1 1\n-1 1 -1\n-1 1 1\n1 -1 -1\n1 -1 1\n1 1 -1\n1 1 1\n4 0 1 3 2\n4 6 7 5 4\n4 5 7 3 1\n4 0 2 6 4\n4 4 5 1 0\n4 3 7 6 2",
        "broken": "OFF\n4 1 0\n1 1 1\n1 -1 -1\n-1 1 -1\n-1 -1 1\n0",
    }.items():
        fn.write_text(off)
        print(f"{fn} is now {name}")
        sleep(delay)
``` 
2.  open the file with `f3d --watch /tmp/watched.off`
3.  observe the file _does_ reload when changing from a tetrahedron to a cube to a broken file
4.  observe the file does _not_ reload as a tetrahedron after being broken, press `up` to reload manually

**Expected behavior**
The file should reload every time even after it failed to load

**System Information:**
N/A

**F3D Information**
`3.0`, `3.1`

**Additional context**
The bug is due to supported files that fail to load being treated as unsupported.

The following diff could be the base of a quick and dirty fix as it does allow the broken file to reload automatically:
```diff
diff --git a/application/F3DStarter.cxx b/application/F3DStarter.cxx
index 9b76ea17..37facf28 100644
--- a/application/F3DStarter.cxx
+++ b/application/F3DStarter.cxx
@@ -1456,10 +1456,6 @@ void F3DStarter::LoadFileGroup(
             "Loading animation time: ", this->Internals->AppOptions.AnimationTime.value());
           scene.loadAnimationTime(this->Internals->AppOptions.AnimationTime.value());
         }
-
-        // Update loaded files
-        std::copy(
-          localPaths.begin(), localPaths.end(), std::back_inserter(this->Internals->LoadedFiles));
       }
     }
   }
@@ -1473,6 +1469,9 @@ void F3DStarter::LoadFileGroup(
     unsupported = true;
   }
 
+  // Update loaded files
+  std::copy(localPaths.begin(), localPaths.end(), std::back_inserter(this->Internals->LoadedFiles));
+
   std::string filenameInfo;
   if (this->Internals->LoadedFiles.size() > 0)
   {
@@ -1549,7 +1548,7 @@ void F3DStarter::LoadFileGroup(
   // but there is no way to detect if an option has been set
   // by the user or not.
   f3d::options& options = this->Internals->Engine->getOptions();
-  options.ui.dropzone = this->Internals->LoadedFiles.empty();
+  options.ui.dropzone = unsupported;
   options.ui.filename_info = filenameInfo;
 }
```

However a proper solution would involve distinguishing between actually unsupported files and supported files that failed to load to be able to act accordingly (logging, UI, ...).

### LINKED ISSUE #2354: -watch flag can crash f3d.exe
**Describe the bug**
-watch flag can crash f3d.exe

**To Reproduce**

1.  f3d.exe --input test.obj --watch
2.  rewrite test.obj (with valid obj data)
3.  f3d.exe crash with error below

Faulting application name: f3d.exe, version: 0.0.0.0, time stamp: 0x67ff85fb
Faulting module name: ntdll.dll, version: 10.0.22621.4317, time stamp: 0xf9f266e7
Exception code: 0xc0000005
Fault offset: 0x000000000003f4b1
Faulting process id: 0x0xA5E4
Faulting application start time: 0x0x1DBEB905D4432B4
Faulting application path: E:\download\F3D-3.1.0-Windows-x86_64\bin\f3d.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: aa99a9b7-11a8-4247-beef-ed1b1fa04e7e
Faulting package full name: 
Faulting package-relative application ID: 

**Expected behavior**
f3d keep watching for file changes

**System Information:**

- OS: Microsoft Windows [Version 10.0.22621.4317]
- GPU and GPU driver: 
NVIDIA GeForce RTX 4070 Ti
32.0.15.7270 (NVIDIA 572.70) DCH / Win11 64

**F3D Information**
F3D 3.1.0

F3D - A fast and minimalist 3D viewer
Version: 3.1.0.
Build date: 2025-04-16 10:26:31.
Build system: Windows 64-bits.
Compiler: MSVC 19.43.34808.0.
Module ImGui: ON.
Module OpenEXR: ON.
Module Raytracing: OFF.
VTK version: 9.4.2-1794-g691f4a3c11 (date: 20250329).
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2025 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.

### PR DESCRIPTION
**Pull request by mwestphal**
### Describe your changes

 - Rework handling of invalid files and keep track of the scene status
 - Stop writing [INVALID] in the filename info, the log is available now instead
 - Write [EMPTY] when the scene is empty
 - Support watching an invalid file (fix for #2246)
 - Support watching a non-existent, unsupported or over max-memory file
 - Better logic to avoin unwatching/rewatching all the time (fix for #2354)
 - Add/Improve tests

### Issue ticket number and link if any

Fix #2246
Fix #2354

### Checklist for finalizing the PR

- [x] I have performed a [self-review](https://f3d.app/doc/dev/CODING_STYLE.html) of my code
- [x] I have added [tests](https://f3d.app/doc/dev/TESTING.html) for new features and bugfixes
- [ ] I have added [documentation](https://f3d.app/) for new features
- [ ] If it is a modifying the libf3d API, I have updated bindings
- [ ] If it is a modifying the `.github/workflows/versions.json`, I have updated `timestamp`

### Continuous integration

Please check the checkbox of the CI you want to run, then push again on your branch.

- [x] Style checks
- [x] Fast CI
- [x] Coverage cached CI
- [x] Analysis cached CI
- [x] WASM docker CI
- [x] Android docker CI
- [x] macOS Intel cached CI
- [x] macOS ARM cached CI
- [x] Windows cached CI
- [x] Linux cached CI
- [x] Other cached CI

### CODE REVIEW

**Review by Meakk — APPROVED** [review]

File: application/F3DStarter.cxx [hunk 1]
```diff
@@ -911,16 +911,13 @@ class F3DStarter::F3DInternals
...
-    std::vector<fs::path> parents;
+    std::set<fs::path> parents;
     for (const auto& tmpPath : paths)
     {
       fs::path parentPath = tmpPath.parent_path();
-      if (std::find(parents.begin(), parents.end(), tmpPath) == parents.end())
-      {
-        parents.emplace_back(parentPath);
-      }
+      parents.insert(parentPath);
```
Comment (snoyer) [inline application/F3DStarter.cxx]:
```suggestion
      parents.insert(tmpPath.parent_path());
```

File: application/F3DStarter.cxx [hunk 2]
```diff
@@ -1535,34 +1533,52 @@ void F3DStarter::LoadFileGroup(
...
+              }
+              else
+              {
+                f3d::log::warn(tmpPath.string(), " is not a file of a supported file format");
+              }
+              unsupported = true;
             }
-            unsupported = true;
+          }
+          catch (const fs::filesystem_error& ex)
```
Comment (Meakk) [inline application/F3DStarter.cxx:1578]: any chance we can cover this exception?

File: application/F3DStarter.cxx [hunk 3]
```diff
@@ -1609,44 +1624,51 @@ void F3DStarter::LoadFileGroup(
...
+      const dmon_watch_id& dmonId = it->second;
+      if (dmonId.id > 0 && parentPaths.count(path) == 0)
       {
-        if (dmonId.id > 0)
-        {
-          dmon_unwatch(dmonId);
-        }
+        f3d::log::debug("Stopped watching: ", path.string());
+        dmon_unwatch(dmonId);
+        it = this->Internals->FolderWatchIds.erase(it);
```
Comment (Meakk) [inline application/F3DStarter.cxx:1652]: Can we simplify this logic by iterating backward with `rbegin()` and `rend()`?

File: application/F3DStarter.cxx (hunk 2 above)
Comment (mwestphal) [reply application/F3DStarter.cxx:1578]: As I documented the line below, this is unreachable because we already go through a fs:: call with the filename and the only I know to trigger an exception is by having a long folder name.

I could remove the catch but better safe than sorry.

File: application/F3DStarter.cxx (hunk 3 above)
Comment (mwestphal) [reply application/F3DStarter.cxx:1652]: Its already pretty simple, how would rbegin, rend help ?

Comment (Meakk) [reply application/F3DStarter.cxx:1652]: In order to avoid the `else` block below.

**Review by Meakk — APPROVED** [review]
