### PR TITLE
Compute tangents if not provided in assimp importer

### LINKED ISSUE #603: FBX Normal Mapping is not working
**Describe the bug**
A model with normal maps in FBX format is not shown with a normal map

**To Reproduce**
 1. Open fbx file with normal mapping ([normal.zip](https://github.com/f3d-app/f3d/files/10609684/normal.zip))

 3. Normal mapping is not visible
 4. normal.fbx : no normal, even though normal code is being executed
 
fbx

 5. normal.glb: normal is working great

glb

**Expected behavior**
Normal mapping should be visible

the fbx has been tested in Windows 3D viewer and works great.

### PR DESCRIPTION
**Pull request by Meakk**
Fix #603

### CODE REVIEW

**Review by mwestphal — APPROVED** [review]

File: plugins/assimp/module/vtkF3DAssimpImporter.cxx [hunk 1]
```diff
@@ -553,6 +555,20 @@ class vtkF3DAssimpImporter::vtkInternals
       polyData->GetFieldData()->AddArray(bonesTransform);
     }
 
+    if (mesh->HasNormals() && mesh->HasTextureCoords(0) && !mesh->HasTangentsAndBitangents())
```
Comment (mwestphal) [inline plugins/assimp/module/vtkF3DAssimpImporter.cxx:558]: what if HasNormals is false ? Should we compute them too ?
