### PR TITLE
fix: print error when test record file doesn't exist

### LINKED ISSUE #1231: F3D does not error out when specifying non-existent path on --interaction-test-record
**Describe the bug**
Opening f3d with --interaction-test-record and giving it a path which is a non-existing directory bugs out the program. Escape does not work and the killing the process with Ctrl + C does not generate the log file. Other toggles seems to work correctly

**To Reproduce**
 1. Open the file using `f3d example.glb --interactive-test-record path/does/not/exist/abc.log`
 2. Try closing the program using Escape

**Expected behavior**
Print an error stating that the path does not exist and exit

**System Information:**
 - OS: Gentoo Linux
 - GPU and GPU driver: Intel Corporation Alder Lake-P Integrated Graphics Controller, i915

**F3D Information**
F3D 2.2.1

F3D - A fast and minimalist 3D viewer
Version: 2.2.1-55-g77596024.
Build date: 2024-01-23 03:42:40.
Build system: Linux 64-bits.
Compiler: GNU 13.2.1.
External rendering module: OFF.
Raytracing module: OFF.
VTK version: 9.3.0.
Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2023 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
By Michael Migliore, Mathieu Westphal and Joachim Pouderoux.

**Additional context**
The attached video shows this behaviour when specifying an non-existent path

https://github.com/f3d-app/f3d/assets/14817339/00466046-2219-4015-be61-ccdca2fb359d

### PR DESCRIPTION
**Pull request by chirag-droid**
## Fixes

#1231 

## Changes

F3D now errors out when the record file doesn't exist.

### CODE REVIEW

**Comment by Meakk** [comment]
The CI jobs are failing though. It needs to be fixed first.

File: library/src/interactor_impl.cxx [hunk 1]
```diff
@@ -688,6 +688,12 @@ bool interactor_impl::recordInteraction(const std::string& file)
     return false;
   }
 
+  if (!vtksys::SystemTools::FileExists(file))
+  {
+    log::error("Interaction log file to record interactions to does not exist", file);
```
Comment (0x006E) [inline library/src/interactor_impl.cxx:693]: Rather than checking if the file exists,I think we should check if the path is writable or not, because when new interaction tests are created, we specifiy filenames that may not exist yet.

Comment (chirag-droid) [reply library/src/interactor_impl.cxx:693]: I am working on this

**Comment by chirag-droid** [comment]
Should I create a temp file in parent directory and check if it succeeds? or is there a better way

**Comment by chirag-droid** [comment]
wait what happened..

**Comment by mwestphal** [comment]
for the inexistent path, just pick pick an `invalid` dir in the testing dir.

For the path without permissions, you can create a file without write permission in the testing dir and try writing to it.

**Comment by chirag-droid** [comment]
@mwestphal The tests are failing in Windows and Linux GitHub runners. For some reason changing directory permission is not working as expected. On Mac however the permissions are set correctly.

**Comment by mwestphal** [comment]
I tried locally on my linux and this is working fine, strange.

**Comment by mwestphal** [comment]
maybe try putting no permissions at all ?

**Comment by chirag-droid** [comment]
> I tried locally on my linux and this is working fine, strange.

The issue is only happening inside github runners. specifically windows and linux.

In both of these platform cmake fails to set appropriate permission. The test expects a non writable directory.

I have tried running raw `chmod` command and it fails too.

If i remove this test then coverage test will fail

**Comment by mwestphal** [comment]
Let's remove this test. Coverage reduction is ok when justified

**Comment by chirag-droid** [comment]
https://github.com/f3d-app/f3d/blob/b40fba3e10401e34816926818a29e47571926777/library/src/interactor_impl.cxx#L684-L689

This todo can be removed now?

**Review by mwestphal — APPROVED** [review]
