### PR TITLE
OCCT fixes for edges and colors

### LINKED ISSUE #271: Missing colors with STEP file
**Describe the bug**
Colors from STEP files not represented

**To Reproduce**
Steps to reproduce the behavior: Open the file

Screenshot_20220427_220832

The STEP file can be exported here: https://cad.onshape.com/documents/0e914e25b085e45c5ea9909d/w/0e60af9e7041cf3f62561d86/e/3a0581e7443351b7b7ca6a93?renderMode=0&uiState=6269a3d56959b541b9d18cb2 

**Expected behavior**
Screenshot_20220427_221022

**System Information:**
 - OS: Kubuntu 22.04
 - GPU and GPU driver: AMD Renoir

**F3D Information**
```
f3d 1.2.1

F3D - A fast and minimalist 3D viewer
Version: 1.2.1
Build date: 2021-12-13 23:27:53
System: Linux-5.11.0-1022-azure x86_64
Compiler: GNU 7.5.0
RayTracing module: OFF
Exodus module: ON
OpenCASCADE module: 7.6.0 (no metadata)
Assimp module: 5.1.0
VTK version: 9.1.20211124 (build 20211124)

Copyright (C) 2019-2021 Kitware SAS.
Copyright (C) 2021-2022 Michael Migliore, Mathieu Westphal.
License BSD-3-Clause.
Written by Michael Migliore, Mathieu Westphal and Joachim Pouderoux.
```

### PR DESCRIPTION
**Pull request by snoyer**
The color of a face/edge in a STEP file can be stored on the parent shape instead of the face/edge itself, so we need to check that as a fallback.

would fix #271, also fixes an off-by-one oversight on the edges.

Fixing the missing edges possibly makes everything look ugly now as the lines are drawn very thin :(
Not sure what the way forward is here? should the lines be hidden by default and toggled with the "show edges" features instead of it showing the underlying triangulation edges?

### CODE REVIEW

File: plugins/occt/module/vtkF3DOCCTReader.cxx [hunk 1]
```diff
@@ -143,7 +143,8 @@ class vtkF3DOCCTReader::vtkInternals
         {
           std::array<unsigned char, 3> rgb = { 0, 0, 0 };
           Quantity_Color aColor;
-          if (this->ColorTool->GetColor(edge, XCAFDoc_ColorCurv, aColor))
+          if (this->ColorTool->GetColor(edge, XCAFDoc_ColorCurv, aColor) ||
```
Comment (Meakk) [inline plugins/occt/module/vtkF3DOCCTReader.cxx:146]: Oh ok, so the logic is to fallback on the shape color if there's no color on the cell?

**Review by Meakk — APPROVED** [review]

File: plugins/occt/module/vtkF3DOCCTReader.cxx (hunk 1 above)
Comment (Meakk) [reply plugins/occt/module/vtkF3DOCCTReader.cxx:146]: You described it in the PR description, I got it 👍

File: testing/data/xcaf-colors.stp
Comment (mwestphal) [inline testing/data/xcaf-colors.stp:1]: where is this file coming from ?

Comment (snoyer) [reply testing/data/xcaf-colors.stp:1]: made it up just for you:

```cpp
#include <BRepPrimAPI_MakeBox.hxx>
#include <Quantity_Color.hxx>
#include <STEPCAFControl_Writer.hxx>
#include <TDocStd_Document.hxx>
#include <TopExp.hxx>
#include <TopTools_IndexedMapOfShape.hxx>
#include <TopoDS.hxx>
#include <XCAFApp_Application.hxx>
#include <XCAFDoc_ColorTool.hxx>
#include <XCAFDoc_ColorType.hxx>
#include <XCAFDoc_DocumentTool.hxx>
#include <XCAFDoc_ShapeTool.hxx>

#include <iostream>
#include <vector>

TopoDS_Shape make_box(int col, int row) {
  return BRepPrimAPI_MakeBox(gp_Pnt(col * 1.5, row * 1.5, 0), 1, 1, 1);
}

std::vector<TopoDS_Face> get_faces(TopoDS_Shape &shape) {
  std::vector<TopoDS_Face> faces_vector;
  TopTools_IndexedMapOfShape faces;
  TopExp::MapShapes(shape, TopAbs_FACE, faces);
  for (int i = 1; i <= faces.Extent(); ++i)
    faces_vector.push_back(TopoDS::Face(faces(i)));
  return faces_vector;
}

int main() {
  Handle(TDocStd_Document) doc;
  Handle(XCAFApp_Application) app = XCAFApp_Application::GetApplication();
  app->NewDocument("MDTV-XCAF", doc);

  Handle(XCAFDoc_ShapeTool) shapeTool = XCAFDoc_DocumentTool::ShapeTool(doc->Main());
  Handle(XCAFDoc_ColorTool) colorTool = XCAFDoc_DocumentTool::ColorTool(doc->Main());

  Quantity_Color red(1.0, 0.0, 0.0, Quantity_TypeOfColor::Quantity_TOC_RGB);
  Quantity_Color green(0.0, 1.0, 0.0, Quantity_TypeOfColor::Quantity_TOC_RGB);
  Quantity_Color blue(0.0, 0.0, 1.0, Quantity_TypeOfColor::Quantity_TOC_RGB);

  XCAFDoc_ColorType color_types[3] = {XCAFDoc_ColorType::XCAFDoc_ColorGen,
                                      XCAFDoc_ColorType::XCAFDoc_ColorSurf,
                                      XCAFDoc_ColorType::XCAFDoc_ColorCurv};

  /* colored boxes */
  for (int i = 0; i < 3; ++i) {
    TopoDS_Shape box = make_box(i, 0);
    shapeTool->SetShape(shapeTool->NewShape(), box);
    colorTool->SetColor(box, red, color_types[i]);
  }

  /* boxes with colored faces */
  for (int i = 0; i < 3; ++i) {
    TopoDS_Shape box = make_box(i, 1);
    shapeTool->SetShape(shapeTool->NewShape(), box);
    for (auto face : get_faces(box))
      colorTool->SetColor(face, blue, color_types[i]);
  }

  /* colored boxes with colored faces */
  for (int i = 0; i < 3; ++i) {
    TopoDS_Shape box = make_box(i, 2);
    shapeTool->SetShape(shapeTool->NewShape(), box);
    colorTool->SetColor(box, green, XCAFDoc_ColorType::XCAFDoc_ColorGen);
    for (auto face : get_faces(box))
      colorTool->SetColor(face, blue, color_types[i]);
  }

  STEPCAFControl_Writer *writer = new STEPCAFControl_Writer();
  writer->SetColorMode(true);
  writer->Perform(doc, "/tmp/xcaf-colors.stp");

  return 0;
}
```

File: plugins/occt/module/vtkF3DOCCTReader.cxx (hunk 1 above)
Comment (snoyer) [reply plugins/occt/module/vtkF3DOCCTReader.cxx:146]: hopefully we don't have to fallback higher up on compound shapes and whatnot... I guess we'll see if examples show up in the wild

**Review by mwestphal — APPROVED** [review]
