### PR TITLE
Fix segfault on reload with progress bar

### LINKED ISSUE #761: Reloading a file while using a progress bar causes a segfault
**Describe the bug**
Loading **again** a file that shows a progress bar causes a segfault in SSAO pass

**To Reproduce**
1. Download  [key.zip](https://github.com/f3d-app/f3d/files/11308638/key.zip)
3. run `f3d "95165A619_Strong-Hold Quick-Release Pin.step"` (notice the progress bar)
4. Press up

**Expected behavior**
No segfault

**System Information:**
 - OS: ArchLinux
 - GPU and GPU driver:

**F3D Information**
Paste the content of `f3d --version`: master

**Additional context**

```
Thread 1 "f3d" received signal SIGSEGV, Segmentation fault.
0x00007ffff63e605e in vtkOpenGLRenderPass::PreRender (this=0x555555d50fa0, s=0x7fffffff85d0) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkOpenGLRenderPass.cxx:74
74          vtkInformation* info = prop->GetPropertyKeys();
(gdb) bt
#0  0x00007ffff63e605e in vtkOpenGLRenderPass::PreRender (this=0x555555d50fa0, s=0x7fffffff85d0) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkOpenGLRenderPass.cxx:74
#1  0x00007ffff64b284f in vtkSSAOPass::RenderDelegate (this=0x555555d50fa0, s=0x7fffffff85d0, w=1276, h=1410) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkSSAOPass.cxx:220
#2  0x00007ffff64b446d in vtkSSAOPass::Render (this=0x555555d50fa0, s=0x7fffffff85d0) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkSSAOPass.cxx:499
#3  0x00007ffff64b75cb in vtkSequencePass::Render (this=0x555555ce4530, s=0x7fffffff85d0) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkSequencePass.cxx:71
#4  0x00007ffff629b421 in vtkCameraPass::Render (this=0x5555561405b0, s=0x7fffffff85d0) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkCameraPass.cxx:145
#5  0x00007ffff62d28e6 in vtkDepthImageProcessingPass::RenderDelegate (this=0x555556156e00, s=0x7fffffff89c0, width=1276, height=1410, newWidth=1276, newHeight=1410, fbo=0x55555630fde0, 
    colortarget=0x555556566f60, depthtarget=0x555555ce0880) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkDepthImageProcessingPass.cxx:131
#6  0x00007ffff62effbd in vtkFramebufferPass::Render (this=0x555556156e00, s=0x7fffffff89c0) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkFramebufferPass.cxx:145
#7  0x00007ffff7da389d in vtkF3DRenderPass::Render (this=0x555556153700, s=0x7fffffff8a80) at /home/glow/dev/f3d/f3d/src/library/VTKExtensions/Rendering/vtkF3DRenderPass.cxx:213
#8  0x00007ffff6305344 in vtkImageProcessingPass::RenderDelegate (this=0x5555574119c0, s=0x7fffffff8f60, width=1276, height=1410, newWidth=1276, newHeight=1410, fbo=0x555556172b10, 
    target=0x555556ab6a50) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkImageProcessingPass.cxx:179
#9  0x00007ffff64ed2fe in vtkToneMappingPass::Render (this=0x5555574119c0, s=0x7fffffff8f60) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkToneMappingPass.cxx:118
#10 0x00007ffff6325c88 in vtkOpenGLFXAAPass::Render (this=0x55555741db30, s=0x7fffffff8f60) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkOpenGLFXAAPass.cxx:40
#11 0x00007ffff64002bd in vtkOpenGLRenderer::DeviceRender (this=0x55555602a1a0) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkOpenGLRenderer.cxx:285
#12 0x00007ffff4c4ce81 in vtkRenderer::Render (this=0x55555602a1a0) at /home/glow/dev/vtk/vtk1/src/Rendering/Core/vtkRenderer.cxx:385
#13 0x00007ffff7d77850 in vtkF3DRenderer::Render (this=0x55555602a1a0) at /home/glow/dev/f3d/f3d/src/library/VTKExtensions/Rendering/vtkF3DRenderer.cxx:1045
#14 0x00007ffff4c6b13b in vtkRendererCollection::Render (this=0x555555728490) at /home/glow/dev/vtk/vtk1/src/Rendering/Core/vtkRendererCollection.cxx:52
#15 0x00007ffff4c29586 in vtkRenderWindow::DoStereoRender (this=0x555555716340) at /home/glow/dev/vtk/vtk1/src/Rendering/Core/vtkRenderWindow.cxx:356
#16 0x00007ffff4c2931a in vtkRenderWindow::Render (this=0x555555716340) at /home/glow/dev/vtk/vtk1/src/Rendering/Core/vtkRenderWindow.cxx:316
#17 0x00007ffff63fde2d in vtkOpenGLRenderWindow::Render (this=0x555555716340) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx:2772
#18 0x00007ffff6507fca in vtkXOpenGLRenderWindow::Render (this=0x555555716340) at /home/glow/dev/vtk/vtk1/src/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx:1656
#19 0x00007ffff4c345ba in vtkRenderWindowInteractor::Render (this=0x55555571acf0) at /home/glow/dev/vtk/vtk1/src/Rendering/Core/vtkRenderWindowInteractor.cxx:178
#20 0x00007ffff7106761 in vtkAbstractWidget::Render (this=0x555555cd17f0) at /home/glow/dev/vtk/vtk1/src/Interaction/Widgets/vtkAbstractWidget.cxx:267
#21 0x00007ffff7d23854 in f3d::detail::loader_impl::internals::CreateProgressRepresentationAndCallback(f3d::detail::loader_impl::internals::ProgressDataStruct*, vtkImporter*, f3d::detail::interactor_impl*)::{lambda(vtkObject*, unsigned long, void*, void*)#1}::operator()(vtkObject*, unsigned long, void*, void*) const (__closure=0x0, clientData=0x7fffffffd440, callData=0x7fffffff9a90)
    at /home/glow/dev/f3d/f3d/src/library/src/loader_impl.cxx:56
#22 0x00007ffff7d2388f in f3d::detail::loader_impl::internals::CreateProgressRepresentationAndCallback(f3d::detail::loader_impl::internals::ProgressDataStruct*, vtkImporter*, f3d::detail::interactor_impl*)::{lambda(vtkObject*, unsigned long, void*, void*)#1}::_FUN(vtkObject*, unsigned long, void*, void*) () at /home/glow/dev/f3d/f3d/src/library/src/loader_impl.cxx:58
#23 0x00007ffff099c653 in vtkCallbackCommand::Execute (this=0x5555573ec150, caller=0x555555717da0, event=6, callData=0x7fffffff9a90)
    at /home/glow/dev/vtk/vtk1/src/Common/Core/vtkCallbackCommand.cxx:42

```

### PR DESCRIPTION
**Pull request by mwestphal**
- Fix a segfault on reload with progress bar
- **Feature is not behaving as expected, on reload, the progress bar DO NOT APPEAR but nothing is visible during the reload**
- Add progress bar smoke test
- Fix #761

### CODE REVIEW

File: library/src/loader_impl.cxx [hunk 1]
```diff
@@ -47,7 +47,8 @@ class loader_impl::internals
         progressData->timer->StopTimer();
         vtkProgressBarWidget* widget = progressData->widget;
         // Only show and render the progress bar if loading takes more than 0.15 seconds
-        if (progressData->timer->GetElapsedTime() > 0.15)
+        if (progressData->timer->GetElapsedTime() > 0.15 ||
+          std::getenv("CTEST_PROGRESS_BAR_TESTING") != nullptr)
```
Comment (Meakk) [inline library/src/loader_impl.cxx:51]: what about using `vtksys::SystemTools::GetEnv` instead of hiding `_CRT_SECURE_NO_WARNINGS` warnings?

File: library/src/loader_impl.cxx [hunk 2]
```diff
@@ -47,7 +47,8 @@ class loader_impl::internals
         progressData->timer->StopTimer();
         vtkProgressBarWidget* widget = progressData->widget;
         // Only show and render the progress bar if loading takes more than 0.15 seconds
-        if (progressData->timer->GetElapsedTime() > 0.15)
+        if (progressData->timer->GetElapsedTime() > 0.15 ||
+          vtksys::SystemTools::GetEnv("CTEST_PROGRESS_BAR_TESTING") != nullptr)
```
Comment (Meakk) [inline library/src/loader_impl.cxx:51]: sorry to be a pain, what about using `HasEnv` instead of `GetEnv() != nullptr`?

**Review by Meakk — APPROVED** [review]
