### PR TITLE
Fix blur shader

### LINKED ISSUE #217: When render with hdr background and '-u' , the background could be stretched (wrong x/y ratio)
**Describe the bug**
When render with hdr skybox photo, and using different x/y for the output picture, we can see the background is stretched.

First, the pictures without -u, I don't see obvious issues, background picture looks fine.
1200x1200:
1200x1200

2400x1200:
2400x1200

However, after turn on background blur, the second one looks wrong (the light shape is oval):
1200x1200 with -u:
1200x1200u

2400x1200 with -u:
2400x1200u

 
**To Reproduce**

```
f3d --input WaterBottle.glb --output 2400x1200u.png --camera-position=0.584518,0.0,0.0 -u -t --hdri christmas.hdr --resolution=2400,1200 --dry-run
```
background img: 
[christmas.hdr.zip](https://github.com/f3d-app/f3d/files/7908256/christmas.hdr.zip)

**Expected behavior**

background should look similar with different resolution

**System Information:**
 - OS: Linux 
 - GPU and GPU driver: None

**F3D Information**
Paste the content of `f3d --version`:

1.2.1

### PR DESCRIPTION
**Pull request by Meakk**
Fixes #217

### CODE REVIEW

**Review by mwestphal — APPROVED** [review]

File: src/library/vtkF3DRenderPass.cxx [hunk 1]
```diff
@@ -229,13 +229,15 @@ void vtkF3DRenderPass::Blend(const vtkRenderState* s)
...
+              "  ivec2 textureSize = textureSize(texBackground, 0);\n"
+              "  float ratio = float(textureSize.x) / float(textureSize.y);\n"
               "  vec3 acc = vec3(0.0);\n"
               "  float factor = radius / sqrt(float(SAMPLES));\n"
               "  for (int i = 0; i < SAMPLES; i++)\n"
               "  {\n"
               "    float theta = float(i) * GOLDEN_ANGLE;\n"
               "    float r = factor * sqrt(float(i));\n"
-              "    vec2 pt = vec2(r * cos(theta), r * sin(theta));\n"
+              "    vec2 pt = vec2(r * cos(theta) / ratio, r * sin(theta));\n"
```
Comment (mwestphal) [inline src/library/vtkF3DRenderPass.cxx:240]: ratio is not taken into account with y coord ?

Comment (Meakk) [reply src/library/vtkF3DRenderPass.cxx:240]: No it shouldn't
